words = {
    "start_words": {
        "Dog": ["собака", "пес", "песик", "собачка"],
        "Cat": ["кішка", "кіт", "котик", "кішечка"],
        "Apologize": ["Вибачатися", "Вибачатися"],
        "Basic": ["Основний", "Базовий"],
        "Chat": ["Балакати", "Чат", "Говорити", "Базікати"],
        "Delicious": ["Смачний"],
        "Excited": ["Захоплений", "Зацікавлений"],
        "Friendly": ["Дружелюбний", "Дружній"],
        "Greet": ["Вітати", "Привітати"],
        "Happy": ["Щасливий", "Веселий"],
        "Invite": ["Запрошувати"],
        "Journey": ["Подорож"],
        "Kind": ["Ласкавий", "Добрий"],
        "Laugh": ["Сміятися", "Реготати"],
        "Mistake": ["Помилка"],
        "Nice ": ["Миленький", "Добрий", "Милий", "Гарний", "Добрий"],
        "Open": ["Відкритий", "Відчинений"],
        "Polite": ["Ввічливий", "Увічливий"],
        "Question": ["Питання", "Запитити", "Запитання", "Питати"],
        "Read": ["Читати", "Прочитати", "Читав", "Прочитав"],
        "Smile": ["Посмішка", "Посміхнися", "Усміхнися", "Посміхнись", "Усміхнись", "Усмішка"],
        "Thankful": ["Вдячний"]
    },
    "food_words": {
        "Breakfast": ["Сніданок"],
        "Lunch": ["Обід"],
        "Dinner": ["Вечеря"],
        "Meal": ["Страва"],
        "Snack": ["Перекус"],
        "Appetizer": ["Закуска"],
        "Main course": ["Головна страва"],
        "Dessert": ["Десерт"],
        "Beverage": ["Напій"],
        "Fruit": ["Фрукт"],
        "Vegetable": ["Овоч"],
        "Bread": ["Хліб"],
        "Cheese": ["Сир"],
        "Meat": ["М'ясо"],
        "Fish": ["Риба"],
        "Soup": ["Суп"],
        "Salad": ["Салат"],
        "Spice": ["Спеції"],
        "Sweet": ["Солодкий"],
        "Sour": ["Кислий"]
    },
    "trip_words": {
        "Airport": ["Аеропорт"],
        "Ticket": ["Квиток"],
        "Passport": ["Паспорт"],
        "Hotel": ["Готель"],
        "Taxi": ["Таксі"],
        " Map": ["Карта", "Мапа"],
        "Suitcase": ["Валіза", "Багаж"],
        "Sightseeing": ["Огляд пам'яток", "Дивитися на пам'ятки"],
        "Guide": ["Гід", "Провідник"],
        "Beach": ["Пляж"],
        "Train": ["Поїзд", "Потяг"],
        "Bus": ["Автобус"],
        "Restaurant": ["Ресторан", "Меню"],
        "City": ["Місто"],
        "Park": ["Парк"],
        "Tourist": ["Турист"],
        " Excursion": ["Екскурсія"],
        "Currency": ["Валюта"],
        "Direction": ["Напрямок", "Направлення"]
    },
    "conversation_words": {
        "Greet": ["Вітати", "Вітаю", "Привіт"],
        "Ask": ["Питати", "Запитати"],
        "Answer": ["Відповідати", "Відповідь", "Відповісти"],
        "Listen": ["Слухати", "Прислуховуватись"],
        "Speak": ["Говорити", "Розмовляти"],
        "Understand": ["Розуміти"],
        "Discuss": ["Обговорювати"],
        "Explain": ["Пояснювати"],
        "Introduce": ["Представляти"],
        "Apologize": ["Вибачатися"],
        "Appreciate": ["Цінувати"],
        "Encourage": ["Заохочувати"],
        "Compliment": ["Хвалити"],
        "Argue": ["Сперечатися"],
        "Agree": ["Згоджуватися"],
        "Disagree": ["Незгоджуватися"],
        "Suggest": ["Пропонувати"],
        "Admire": ["Поважати"]
    },
    "colors_words": {
        "red": ["червоний"],
        "blue": ["синій"],
        "green": ["зелений"],
        "yellow": ["жовтий"],
        "orange": ["помаранчевий"],
        "purple": ["пурпурний"],
        "pink": ["рожевий"],
        "brown": ["коричневий"],
        "white": ["білий"],
        "black": ["чорний"],
        "gray": ["сірий"],
        "silver": ["сріблястий"],
        "gold": ["золотий"],
        "violet": ["фіолетовий"],
        "indigo": ["індіго"],
        "turquoise": ["бірюзовий"],
        "maroon": ["костяновий"],
        "cyan": ["циановий"],
        "magenta": ["пурпурний"],
        "lime": ["лаймовий"]
    },
    "animals_theme_words": {
        "endangered species": ["види, що перебувають під загрозою"],
        "biodiversity": ["біорізноманіття"],
        "animal welfare": ["добробут тварин"],
        "wildlife conservation": ["збереження дикої природи"],
        "zoology": ["зоологія"],
        "ecosystem": ["екосистема"],
        "predator": ["хижак"],
        "prey": ["здобич"],
        "migration": ["міграція"],
        "habitat destruction": ["знищення місць існування"],
        "poaching": ["браконьєрство"],
        "marine life": ["морське життя"],
        "pet adoption": ["усиновлення домашніх тварин"],
        "animal behavior": ["поведінка тварин"],
        "conservation status": ["статус збереження"],
        "exotic pets": ["екзотичні домашні тварини"],
        "animal rights": ["права тварин"],
        "invasive species": ["інвазивні види"],
        "zoological parks": ["зоопарки"],
        "bird watching": ["спостереження за птахами"],
        "mammals": ["ссавці"]
    },
    "it_words": {
        "programming languages": ["мови програмування"],
        "web development": ["розробка веб-сайтів"],
        "software development": ["розробка програмного забезпечення"],
        "data science": ["наука про дані"],
        "machine learning": ["машинне навчання"],
        "artificial intelligence": ["штучний інтелект"],
        "cybersecurity": ["кібербезпека"],
        "cloud computing": ["хмарне обчислення"],
        "networking": ["мережеві технології"],
        "database management": ["управління базами даних"],
        "front-end development": ["розробка фронтенду"],
        "back-end development": ["розробка бекенду"],
        "mobile app development": ["розробка мобільних додатків"],
        "agile methodology": ["гнучка методологія"],
        "version control": ["системи контролю версій"],
        "user experience (UX)": ["користувацький досвід (UX)"],
        "responsive design": ["респонсив дизайн"],
        "virtualization": ["віртуалізація"],
        "Internet of Things (IoT)": ["Інтернет речей (IoT)"],
        "big data": ["великі дані"],
        "IT project management": ["управління ІТ-проектами"]
    },
    "school_words": {
        "classroom": ["класна кімната"],
        "teacher": ["вчитель"],
        "student": ["учень"],
        "lesson": ["урок"],
        "homework": ["домашнє завдання"],
        "exam": ["екзамен"],
        "school subjects": ["шкільні предмети"],
        "mathematics": ["математика"],
        "science": ["наука"],
        "history": ["історія"],
        "geography": ["географія"],
        "language arts": ["мови та література"],
        "physical education": ["фізична культура"],
        "music": ["музика"],
        "art": ["мистецтво"],
        "computer science": ["інформатика"],
        "school supplies": ["шкільні приладдя"],
        "backpack": ["рюкзак"],
        "notebook": ["зошит"],
        "pen": ["ручка"],
        "pencil": ["олівець"],
        "desk": ["парта"],
        "blackboard": ["дошка"],
        "school uniform": ["шкільна форма"],
        "friends": ["друзі"],
        "break time": ["перерва"],
        "lunch": ["обід"],
        "extracurricular activities": ["позакласні заходи"]
    },
    "sport_words": {
        "football": ["футбол"],
        "basketball": ["баскетбол"],
        "tennis": ["теніс"],
        "swimming": ["плавання"],
        "cycling": ["велосипедний спорт"],
        "running": ["біг"],
        "gymnastics": ["гімнастика"],
        "volleyball": ["волейбол"],
        "skiing": ["лижі"],
        "athletics": ["легка атлетика"],
        "weightlifting": ["важка атлетика"],
        "karate": ["карате"],
        "yoga": ["йога"],
        "surfing": ["серфінг"],
        "boxing": ["бокс"],
        "hiking": ["піший туризм"],
        "climbing": ["алпінізм"],
        "table tennis": ["настільний теніс"],
        "badminton": ["бадмінтон"],
        "martial arts": ["бойові мистецтва"],
        "athletic shoes": ["спортивне взуття"],
        "sports equipment": ["спортивне обладнання"],
        "scoreboard": ["табло"],
        "coach": ["тренер"],
        "team": ["команда"],
        "athlete": ["спортсмен/спортсменка"],
        "stadium": ["стадіон"],
        "medal": ["медаль"],
        "competition": ["змагання"],
        "champion": ["чемпіон"],
        "victory": ["перемога"],
        "defeat": ["поразка"]
    },
    "music_words": {
        "music": ["музика"],
        "genre": ["жанр"],
        "artist": ["виконавець"],
        "album": ["альбом"],
        "song": ["пісня"],
        "lyrics": ["текст пісні"],
        "melody": ["мелодія"],
        "instrument": ["інструмент"],
        "orchestra": ["оркестр"],
        "composer": ["композитор"],
        "concert": ["концерт"],
        "beat": ["ритм"],
        "harmony": ["гармонія"],
        "musician": ["музикант"],
        "performance": ["виступ"],
        "dance": ["танець"],
        "music festival": ["музичний фестиваль"],
        "record label": ["музичний лейбл"],
        "DJ": ["діджей"],
        "soundtrack": ["саундтрек"]
    },
    "house_words": {
        "apartment": ["квартира"],
        "living room": ["вітальня"],
        "bedroom": ["спальня"],
        "kitchen": ["кухня"],
        "bathroom": ["ванна кімната"],
        "balcony": ["балкон"],
        "furniture": ["меблі"],
        "bed": ["ліжко"],
        "sofa": ["диван"],
        "table": ["стіл"],
        "chair": ["стілець"],
        "wardrobe": ["шафа"],
        "window": ["вікно"],
        "door": ["двері"],
        "floor": ["підлога"],
        "ceiling": ["стеля"],
        "lamp": ["лампа"],
        "mirror": ["дзеркало"],
        "carpet": ["ковер"],
        "heating": ["опалення"],
        "air conditioning": ["кондиціонер"],
        "rent": ["оренда"],
        "neighbor": ["сусід"],
        "utilities": ["комунальні послуги"]
    },
    "job_words": {
        "job": ["робота"],
        "employer": ["роботодавець"],
        "employee": ["співробітник"],
        "office": ["офіс"],
        "colleague": ["колега"],
        "boss": ["керівник"],
        "workplace": ["робоче місце"],
        "meeting": ["зустріч"],
        "deadline": ["строк виконання"],
        "salary": ["зарплата"],
        "promotion": ["продвиження"],
        "resume": ["резюме"],
        "interview": ["співбесіда"],
        "work hours": ["години роботи"],
        "overtime": ["переробка"],
        "job satisfaction": ["задоволеність роботою"],
        "career": ["кар'єра"],
        "skills": ["навички"],
        "training": ["навчання"],
        "work-life balance": ["баланс роботи та особистого життя"],
        "telecommuting": ["телекомутація"],
        "benefits": ["переваги"],
        "retirement": ["виходження на пенсію"],
        "vacation": ["відпустка"]
    },
    "film_words": {
        "movies": ["фільми"],
        "genre": ["жанр"],
        "director": ["режисер"],
        "actor": ["актор"],
        "actress": ["акторка"],
        "script": ["сценарій"],
        "scene": ["сцена"],
        "plot": ["сюжет"],
        "cinematography": ["кінематографія"],
        "soundtrack": ["саундтрек"],
        "award": ["нагорода"],
        "premiere": ["прем'єра"],
        "sequel": ["продовження"],
        "animation": ["анімація"],
        "box office": ["касова збірка"],
        "critic": ["критик"],
        "rating": ["рейтинг"]
    },
    "fasion_words": {
        "fashion": ["мода"],
        "style": ["стиль"],
        "designer": ["дизайнер"],
        "clothing": ["одяг"],
        "accessories": ["аксесуари"],
        "trend": ["тренд"],
        "runway": ["пасерин"],
        "couture": ["вишуканий одяг"],
        "haute couture": ["вища мода"],
        "brand": ["бренд"],
        "model": ["модель"],
        "fabric": ["тканина"],
        "sewing": ["шиття"],
        "wardrobe": ["гардероб"],
        "makeup": ["макіяж"],
        "style icon": ["ікона стилю"],
        "fashion show": ["показ мод"],
        "street style": ["міський стиль"],
        "vogue": ["вог"],
        "editorial": ["редакційний матеріал"]
    }
}